### PR TITLE
Add CategoryChannel.sort() + CategoryChannel.alphabetize()

### PR DESCRIPTION
**Pull request by diceroll123**
### Description
- dds `sort` function to `CategoryChannel`, a la `list.sort()`
- Adds `alphabetize` helper function.

Adds necessary touches to description + examples of module.

### Checklist
- [x] This PR has been tested.

### CODE REVIEW

**Review by NCPlayz — COMMENTED** [review]
Maybe have an alias for `alphabetise`

**Review by ShineyDev — CHANGES_REQUESTED** [review]
A `sort` method mimicking `list.sort` and family would be approved by me.

**Comment by diceroll123** [comment]
> A `sort` method mimicking `list.sort` and family would be approved by me.

Huh... I think I'll pivot this PR to have a sort as well with a couple helper methods like alphabeti[z|s]e. Good idea!

**Review by ShineyDev — APPROVED** [review]
This helper method seems pretty trivial, but this LGTM. I'll let @NCPlayz merge this after a final review.

**Review by NCPlayz — APPROVED** [review]

**Pull request merged**
